SELECT employee.region.id as `Business Unit Number`,
employee.region.name as `Business Unit`,
position.account.parentAccount.name as `Customer Name`,
position.account.customId as `WorkSite Number`,
position.account.name as `Worksite Name`,
position.customId as `Position Number`,
position.name as `Position Name`,
summary.billTotal as `Revenue`,
summary.payTotal as `Payroll`,
((summary.payTotal)/(summary.billTotal))*100 as `Direct Percentage`,
payableHours as `Paid Hours`,
billableHours as `Billed Hours`,
plannedDurationHours as `Contracted Hours`,
(payableHours)-(billableHours) as `Non Billed Hours`,
overtimeHours as `Paid OT Hours`,
summary.payOvertimeImpact as `Paid OT Dollars`,
summary.billOvertimeHours as `Billed OT Hours`,
summary.billOvertimeImpact as `Billed OT Dollars`,
summary.payHolidayHours as `Paid Holiday Hours`,
summary.payHolidayImpact as `Paid Holiday Dollars`,
summary.billHolidayHours as `Bill Holiday Hours`,
summary.billHolidayImpact as `Bill Holiday Dollars`,
(summary.payOvertimeImpact)/(summary.billOvertimeImpact) as `Non Billed Overtime`,
(summary.billTotal)-(summary.payTotal) as `Profit Dollars`,
(summary.billTotal)/(summary.payTotal) as `Gross Profit Percentage`
from shifts
where summary.billTotal <> " "